version: '3.3'

services:
  nginx:
    image: nginx:1.16
    volumes:
      - ./logs:/var/log/nginx
      - ./html:/usr/share/nginx/html
      - ./nginx-conf:/etc/nginx
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    env_file:
      - ./.env.prod.db
    depends_on:
      - web
  certbot:
    image: certbot/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    
  web:
    # some web app framework.